FROM node:16.13.0-alpine as build
WORKDIR /src
ENV PATH /src/node_modules/.bin:$PATH
COPY package.json ./
COPY yarn.lock ./
RUN apk add git && \
    yarn install --frozen-lockfile && \
    yarn add react-scripts@4.0.3 -g --silent
COPY . ./
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /src/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]