const SEARCH_COLLECTIONS = 'SEARCH_COLLECTIONS' as const;
const CREATE_COLLECTION = 'CREATE_COLLECTION' as const;
const GET_TRENDING_COLLECTIONS = 'GET_TRENDING_COLLECTIONS' as const;
const GET_TOP_COLLECTIONS = 'GET_TOP_COLLECTIONS' as const;
const SEARCH_SINGLE_COLLECTION = 'SEARCH_SINGLE_COLLECTION' as const;

const collectionsActionTypes = {
  SEARCH_COLLECTIONS,
  CREATE_COLLECTION,
  GET_TRENDING_COLLECTIONS,
  GET_TOP_COLLECTIONS,
  SEARCH_SINGLE_COLLECTION,
};

export default collectionsActionTypes;
