const SET_PROMOTION_SETTINGS = 'SET_PROMOTION_SETTINGS';
const SET_PROMOTION_OPTION = 'SET_PROMOTION_OPTION';
const BUY_PROMOTION = 'BUY_PROMOTION';

const promoteActionTypes = {
  SET_PROMOTION_SETTINGS,
  SET_PROMOTION_OPTION,
  BUY_PROMOTION,
};

export default promoteActionTypes;
