const SET_PROMOTION_SETTINGS = 'SET_PROMOTION_SETTINGS';
const SET_PROMOTION_OPTION = 'SET_PROMOTION_OPTION';

const promoteActionTypes = {
  SET_PROMOTION_SETTINGS,
  SET_PROMOTION_OPTION,
};

export default promoteActionTypes;
