export { DiscordIcon } from './Discord';
export { FacebookIcon } from './Facebook';
export { InstagramIcon } from './Instagram';
export { TelegramIcon } from './Telegram';
export { TwitterIcon } from './Twitter';
export { MailOutlinedIcon } from './MailOutlined';
export { GlobeOutlinedIcon } from './GlobeOutlined';
export { TwitterOutlinedIcon } from './TwitterOutlined';
export { InstagramOutlinedIcon } from './InstagramOutlined';
